services:
  resi_cuecontrol:
    image: "ghcr.io/pcs3rd/resi_cuecontrol:sha-a285671"
    ports:
     - "9000:9000/udp"
     - "9001:9001/udp"
     - "8080:8080"
    environment:
     - RESI_USERNAME
     - RESI_PASSWORD
     - CUE_OFFSET_SECONDS
     - DECODER_BUFFER_SEGMENTS
     - HTTP_API_KEY
    restart: unless-stopped
